config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    collection do
      get :search
    end
  end

  root 'movies#index'

end

app/models/concerns/elasticsearch_searchable.rb
require 'elasticsearch/model'

module ElasticsearchSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    def as_indexed_json(options={})
      as_json(except: [:id, :_id])
    end
  end
end

app/models/genre.rb
class Genre
  include Mongoid::Document
  embedded_in :movie, inverse_of: :genres

  field :name, type: String

  validates :name, presence: true
end

app/models/movie.rb
class Movie
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  embeds_many :genres
  accepts_nested_attributes_for :genres, reject_if: :all_blank, autosave: true, autobuild: true

  field :title, type: String
  field :storyline, type: String
  field :release, type: Date
  field :imdb, type: String

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /search/1
  def search
    @movies = Movie.search(params[:search][:q]).records
    render :index
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :storyline, :release, :imdb,
                                    genres_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def genres_format(genres)
    genres.pluck(:name).join(' ')
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Movies Catalogue', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      <%= form_for :search, url: search_movies_path, method: :get, html: {class: :search} do |f| %>
        <%= f.text_field :q, placeholder: 'Search' %>
        <%= f.button :Go %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'New', new_movie_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Movie Catalogue" %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :storyline %><br>
    <%= f.text_area :storyline %>
  </div>
  <div class="field">
    <%= f.label :release %><br>
    <%= f.text_field :release, 'data-provide': :datepicker,
      'data-date-format': 'yyyy-mm-dd',
      'data-date': Date.today, 'data-autoclose': true %>
  </div>
  <div class="field">
    <%= f.label :imdb %><br>
    <%= f.url_field :imdb %>
  </div>

  <label> <%= t('.genre') %></label>
  <div class="field">
    <div>
      <%= link_to_add_association f, :genres %>
    </div>
    <%= f.fields_for :genres do |genre|%>
      <%= render 'genre_fields', f: genre %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

app/views/movies/_genre_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :name, placeholder: 'genre' %>
  <%= link_to_remove_association f %>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Storyline</th>
      <th>Release</th>
      <th>Imdb</th>
      <th>Genres</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie %></td>
        <td><%= movie.storyline %></td>
        <td><%= movie.release %></td>
        <td><%= movie.imdb %></td>
        <td><%= genres_format movie.genres %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Storyline:</strong>
  <%= @movie.storyline %>
</p>

<p>
  <strong>Release:</strong>
  <%= @movie.release %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @movie.imdb %>
</p>

<p>
  <strong>Genres:</strong>
  <%= genres_format @movie.genres %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>